# Generated by Django 3.2.15 on 2023-11-29 12:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name of Client')),
                ('mobile_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('arabic_name', models.CharField(max_length=64, verbose_name='Arabic Name of Client')),
                ('city', models.CharField(max_length=64, verbose_name='city')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date of client register')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats', models.CharField(max_length=64, verbose_name='ATS')),
                ('floors', models.CharField(max_length=64, verbose_name='floors')),
                ('lift_type', models.CharField(max_length=64, verbose_name='Type')),
                ('location', models.URLField(verbose_name='Location')),
                ('size', models.IntegerField(verbose_name='Size')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(choices=[('ATLAS', 'ATLAS'), ('KEILANI_INTERIORS', 'KEILANI_INTERIORS'), ('NAMMOUS', 'NAMMOUS'), ('KCC', 'KCC'), ('SMART', 'SMART'), ('AC', 'AC'), ('LAND_SCAPE', 'LAND_SCAPE'), ('SWIMMING_POOL', 'SWIMMING_POOL')], max_length=255, verbose_name='Name Of Company')),
                ('isMaint', models.BooleanField(default=False, verbose_name='isMaint')),
                ('isManager', models.BooleanField(default=False, verbose_name='isManager')),
                ('isMangerMaint', models.BooleanField(default=False, verbose_name='isMangerMaint')),
                ('isEmp', models.BooleanField(default=False, verbose_name='isEmp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('reminder_datetime', models.DateField()),
                ('notification_sent', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRMapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('SALES', 'SALES'), ('ENG', 'ENG'), ('SIGNED_CONTRACT', 'SIGNED_CONTRACT'), ('MANUFACTURING', 'MANUFACTURING'), ('DELIVERY', 'DELIVERY'), ('INSTALLATION', 'INSTALLATION'), ('MECHANICAL', 'MECHANICAL'), ('ELECTRICAL', 'ELECTRICAL'), ('HANDING_OVER', 'HANDING_OVER'), ('MAINTENANCE', 'MAINTENANCE')], max_length=64, verbose_name='Name of Phase')),
                ('isActive', models.BooleanField(default=False)),
                ('start_date', models.DateField(verbose_name='Phase Date Start')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Phase Date End')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRMapp.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Notes')),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('date', models.DateField(verbose_name='Date of note')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRMapp.contract')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_contract_number', models.CharField(max_length=64, verbose_name='Maintenance Contract Number')),
                ('maintenance_contract_start_date', models.DateField(verbose_name='Maintainance Contract Start')),
                ('maintenance_contract_end_date', models.DateField(verbose_name='Maintainance Contract End')),
                ('maintenance_type', models.CharField(blank=True, choices=[('FREE', 'FREE'), ('PAID', 'PAID')], max_length=255, verbose_name='Maintenance Type')),
                ('contract_value', models.IntegerField()),
                ('spare_parts', models.CharField(choices=[('COMPREHENSIVE', 'COMPREHENSIVE'), ('REGULAR', 'REGULAR')], max_length=255, verbose_name='Spare parts')),
                ('brand', models.CharField(max_length=64, verbose_name='Brand')),
                ('number_of_visits_per_year', models.IntegerField()),
                ('villa_no', models.CharField(max_length=64, verbose_name='Villa Number')),
                ('handing_over_date', models.DateField(verbose_name='Handing Over Date')),
                ('free_maintenance_expiry_date', models.DateField(verbose_name='free maintenance expiry date')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenancelift', to='CRMapp.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('EMERGENCY', 'EMERGENCY'), ('PREDICTIVE PERIODIC', 'PREDICTIVE PERIODIC')], max_length=255, verbose_name='Type of Maintenance ')),
                ('remarks', models.TextField()),
                ('check_image', models.FileField(blank=True, upload_to='')),
                ('date', models.DateField(verbose_name='Date of remark')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRMapp.contract')),
                ('maintenance_lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRMapp.maintenancelift')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry', models.BooleanField(default=True, verbose_name='INQUIRY')),
                ('company_name', models.CharField(choices=[('ATLAS', 'ATLAS'), ('KEILANI_INTERIORS', 'KEILANI_INTERIORS'), ('NAMMOUS', 'NAMMOUS'), ('KCC', 'KCC'), ('SMART', 'SMART'), ('AC', 'AC'), ('LAND_SCAPE', 'LAND_SCAPE'), ('SWIMMING_POOL', 'SWIMMING_POOL')], max_length=255, verbose_name='Name Of Company')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRMapp.client')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRMapp.interest'),
        ),
    ]
