# Generated by Django 3.2.15 on 2023-10-06 17:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name of Client')),
                ('ats', models.CharField(max_length=64, verbose_name='ATS')),
                ('mobile_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('arabic_name', models.CharField(max_length=64, verbose_name='Arabic Name of Client')),
                ('city', models.CharField(max_length=64, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_contract_number', models.CharField(max_length=64, verbose_name='Maintenance Contract Number')),
                ('maintenance_contract_start_date', models.DateTimeField(verbose_name='Maintainance Contract Start')),
                ('maintenance_contract_end_date', models.DateTimeField(verbose_name='Maintainance Contract End')),
                ('type_maintenance', models.CharField(choices=[('FREE', 'FREE'), ('PAID', 'PAID')], max_length=255, verbose_name='maintenance Type')),
                ('contract_value', models.IntegerField()),
                ('spare_parts', models.CharField(choices=[('COMPREHENSIVE', 'COMPREHENSIVE'), ('REGULAR', 'REGULAR')], max_length=255, verbose_name='Spare parts')),
                ('type', models.CharField(max_length=64, verbose_name='Type')),
                ('size', models.IntegerField(verbose_name='Size')),
                ('floors', models.IntegerField(verbose_name='Floors')),
                ('brand', models.CharField(max_length=64, verbose_name='Brand')),
                ('number_of_visits_per_year', models.IntegerField()),
                ('villa_no', models.IntegerField()),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('handing_over_date', models.DateTimeField(verbose_name='Handing Over Date')),
                ('free_maintenance_expiry_date', models.DateTimeField(verbose_name='free maintenance expiry date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('INQUIRY', 'INQUIRY'), ('SALES', 'SALES'), ('ENG', 'ENG'), ('SIGNED_CONTRACT', 'SIGNED_CONTRACT'), ('MANUFACTURING', 'MANUFACTURING'), ('DELIVERY', 'DELIVERY'), ('INSTALLATION', 'INSTALLATION'), ('MECHANICAL', 'MECHANICAL'), ('ELECTRICAL', 'ELECTRICAL'), ('HANDING_OVER', 'HANDING_OVER'), ('MAINTENANCE', 'MAINTENANCE')], max_length=64, verbose_name='Name of Phase')),
                ('isActive', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(verbose_name='Phase Date Start')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Phase Date End')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.elevatorcontract')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Notes')),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('date', models.DateTimeField(verbose_name='Date of note')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.elevatorcontract')),
            ],
        ),
    ]
