# Generated by Django 3.2.15 on 2023-10-18 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name of Client')),
                ('mobile_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('arabic_name', models.CharField(max_length=64, verbose_name='Arabic Name of Client')),
                ('city', models.CharField(max_length=64, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats', models.CharField(max_length=64, verbose_name='ATS')),
                ('floors', models.CharField(max_length=64, verbose_name='floors')),
                ('lift_type', models.CharField(max_length=64, verbose_name='Type')),
                ('location', models.URLField(verbose_name='Location')),
                ('size', models.IntegerField(verbose_name='Size')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('INQUIRY', 'INQUIRY'), ('SALES', 'SALES'), ('ENG', 'ENG'), ('SIGNED_CONTRACT', 'SIGNED_CONTRACT'), ('MANUFACTURING', 'MANUFACTURING'), ('DELIVERY', 'DELIVERY'), ('INSTALLATION', 'INSTALLATION'), ('MECHANICAL', 'MECHANICAL'), ('ELECTRICAL', 'ELECTRICAL'), ('HANDING_OVER', 'HANDING_OVER'), ('MAINTENANCE', 'MAINTENANCE')], max_length=64, verbose_name='Name of Phase')),
                ('isActive', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(verbose_name='Phase Date Start')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Phase Date End')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Notes')),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('date', models.DateTimeField(verbose_name='Date of note')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.contract')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_contract_number', models.CharField(max_length=64, verbose_name='Maintenance Contract Number')),
                ('maintenance_contract_start_date', models.DateTimeField(verbose_name='Maintainance Contract Start')),
                ('maintenance_contract_end_date', models.DateTimeField(verbose_name='Maintainance Contract End')),
                ('maintenance_type', models.CharField(blank=True, choices=[('FREE', 'FREE'), ('PAID', 'PAID')], max_length=255, verbose_name='Maintenance Type')),
                ('contract_value', models.IntegerField()),
                ('spare_parts', models.CharField(choices=[('COMPREHENSIVE', 'COMPREHENSIVE'), ('REGULAR', 'REGULAR')], max_length=255, verbose_name='Spare parts')),
                ('brand', models.CharField(max_length=64, verbose_name='Brand')),
                ('number_of_visits_per_year', models.IntegerField()),
                ('villa_no', models.CharField(max_length=64, verbose_name='Villa Number')),
                ('handing_over_date', models.DateTimeField(verbose_name='Handing Over Date')),
                ('free_maintenance_expiry_date', models.DateTimeField(verbose_name='free maintenance expiry date')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('EMERGENCY', 'EMERGENCY'), ('PREDICTIVE PERIODIC', 'PREDICTIVE PERIODIC')], max_length=255, verbose_name='Type of Maintenance ')),
                ('remarks', models.TextField()),
                ('signature_of_client', models.FileField(blank=True, upload_to='')),
                ('signature_of_supervisor', models.FileField(blank=True, upload_to='')),
                ('signature_of_technician', models.FileField(blank=True, upload_to='')),
                ('date', models.DateTimeField(verbose_name='Date of remark')),
                ('hoist_ropes', models.BooleanField(default=True)),
                ('coupling', models.BooleanField(default=True)),
                ('control_board', models.BooleanField(default=True)),
                ('fuses', models.BooleanField(default=True)),
                ('motor_protection', models.BooleanField(default=True)),
                ('governor_rope', models.BooleanField(default=True)),
                ('is_break', models.BooleanField(default=True)),
                ('gear_bearing', models.BooleanField(default=True)),
                ('piston_units', models.BooleanField(default=True)),
                ('oil_change', models.BooleanField(default=True)),
                ('pumb', models.BooleanField(default=True)),
                ('valve', models.BooleanField(default=True)),
                ('cleanliness', models.BooleanField(default=True)),
                ('buffers', models.BooleanField(default=True)),
                ('limit_switch', models.BooleanField(default=True)),
                ('safety_link', models.BooleanField(default=True)),
                ('under_drive', models.BooleanField(default=True)),
                ('points_of_lubrication', models.BooleanField(default=True)),
                ('landing_calls_signals', models.BooleanField(default=True)),
                ('door_outside_hangers', models.BooleanField(default=True)),
                ('door_close_photocell', models.BooleanField(default=True)),
                ('leveling', models.BooleanField(default=True)),
                ('c_o_p_lights', models.BooleanField(default=True)),
                ('condition_of_car', models.BooleanField(default=True)),
                ('smooth_and_soundless_run', models.BooleanField(default=True)),
                ('start_stop_process', models.BooleanField(default=True)),
                ('door_switch_looking_device', models.BooleanField(default=True)),
                ('clean_lines', models.BooleanField(default=True)),
                ('final_limits', models.BooleanField(default=True)),
                ('car_switch', models.BooleanField(default=True)),
                ('car_insulation', models.BooleanField(default=True)),
                ('safety_device_link_age', models.BooleanField(default=True)),
                ('operation_of_safet_device', models.BooleanField(default=True)),
                ('door_operation', models.BooleanField(default=True)),
                ('door_locks', models.BooleanField(default=True)),
                ('shaft_switches', models.BooleanField(default=True)),
                ('guide_rails_car', models.BooleanField(default=True)),
                ('guide_rails_shoes_car', models.BooleanField(default=True)),
                ('door_inside', models.BooleanField(default=True)),
                ('traveling_cable', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.contract')),
            ],
        ),
    ]
