# Generated by Django 3.2.15 on 2023-11-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of client register'),
        ),
    ]
