# Generated by Django 3.2.15 on 2023-10-19 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0002_auto_20231019_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='contract',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='CRMapp.contract'),
        ),
    ]
