# Generated by Django 3.2.15 on 2023-11-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0002_client_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of client register'),
        ),
    ]
