# Generated by Django 3.2.15 on 2023-11-08 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRMapp', '0002_reminder_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='inquiry',
        ),
        migrations.AddField(
            model_name='interest',
            name='inquiry',
            field=models.BooleanField(default=True, verbose_name='INQUIRY'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(choices=[('ATLAS', 'ATLAS'), ('KEILANI_INTERIORS', 'KEILANI_INTERIORS'), ('NAMMOUS', 'NAMMOUS'), ('KCC', 'KCC'), ('SMART', 'SMART'), ('AC', 'AC'), ('LAND_SCAPE', 'LAND_SCAPE'), ('SWIMMING_POOL', 'SWIMMING_POOL')], max_length=255, verbose_name='Name Of Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
