# Generated by Django 3.2.15 on 2023-10-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0003_alter_phase_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.contract'),
        ),
    ]
