# Generated by Django 3.2.15 on 2023-11-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0003_auto_20231108_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isEmp',
            field=models.BooleanField(default=False, verbose_name='isEmp'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isMaint',
            field=models.BooleanField(default=False, verbose_name='isMaint'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isManager',
            field=models.BooleanField(default=False, verbose_name='isManager'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isMangerMaint',
            field=models.BooleanField(default=False, verbose_name='isMangerMaint'),
        ),
    ]
