# Generated by Django 3.2.15 on 2023-12-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0003_alter_client_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='check_image',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='helper1',
            field=models.CharField(default='', max_length=255, verbose_name='Name Of helper1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='helper2',
            field=models.CharField(default='', max_length=255, verbose_name='Name Of helper1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='technician',
            field=models.CharField(default='', max_length=255, verbose_name='Name Of technician'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='type_name',
            field=models.CharField(choices=[('EMERGENCY', 'EMERGENCY'), ('PREDICTIVE PERIODIC', 'PREDICTIVE PERIODIC')], max_length=255, verbose_name='Type of Maintenance'),
        ),
        migrations.CreateModel(
            name='CheckImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRMapp.maintenance')),
            ],
        ),
    ]
