# Generated by Django 3.2.15 on 2023-11-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0004_auto_20231111_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelift',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.contract'),
        ),
    ]
