# Generated by Django 3.2.15 on 2023-10-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0004_alter_phase_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='ats',
            field=models.CharField(max_length=64, verbose_name='ATS'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='floors',
            field=models.CharField(max_length=64, verbose_name='floors'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='lift_type',
            field=models.CharField(max_length=64, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='location',
            field=models.URLField(verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='size',
            field=models.IntegerField(verbose_name='Size'),
        ),
    ]
