# Generated by Django 3.2.15 on 2023-10-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0005_auto_20231019_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of client register'),
        ),
        migrations.AddField(
            model_name='client',
            name='inquiry',
            field=models.BooleanField(default=True, verbose_name='INQUIRY'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='Name',
            field=models.CharField(choices=[('SALES', 'SALES'), ('ENG', 'ENG'), ('SIGNED_CONTRACT', 'SIGNED_CONTRACT'), ('MANUFACTURING', 'MANUFACTURING'), ('DELIVERY', 'DELIVERY'), ('INSTALLATION', 'INSTALLATION'), ('MECHANICAL', 'MECHANICAL'), ('ELECTRICAL', 'ELECTRICAL'), ('HANDING_OVER', 'HANDING_OVER'), ('MAINTENANCE', 'MAINTENANCE')], max_length=64, verbose_name='Name of Phase'),
        ),
    ]
