# Generated by Django 3.2.15 on 2023-11-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0006_auto_20231124_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelift',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maintenancelift', to='CRMapp.contract'),
        ),
    ]
