# Generated by Django 3.2.15 on 2023-12-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0006_alter_pdfmaintenancecontract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmaintenancecontract',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRMapp.maintenance', unique=True),
        ),
    ]
