# Generated by Django 3.2.15 on 2023-10-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0007_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
