# Generated by Django 3.2.15 on 2023-12-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0008_alter_pdfmaintenancecontract_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='floors',
            field=models.CharField(blank=True, max_length=64, verbose_name='floors'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='lift_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='location',
            field=models.URLField(blank=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='size',
            field=models.IntegerField(blank=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='helper1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name Of helper1'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='helper2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name Of helper1'),
        ),
    ]
