# Generated by Django 3.2.15 on 2023-11-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0009_auto_20231128_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of client register'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.interest'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.client'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.contract'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateTimeField(verbose_name='Date of remark'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_lift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.maintenancelift'),
        ),
        migrations.AlterField(
            model_name='maintenancelift',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maintenancelift', to='CRMapp.contract'),
        ),
        migrations.AlterField(
            model_name='maintenancelift',
            name='free_maintenance_expiry_date',
            field=models.DateTimeField(verbose_name='free maintenance expiry date'),
        ),
        migrations.AlterField(
            model_name='maintenancelift',
            name='handing_over_date',
            field=models.DateTimeField(verbose_name='Handing Over Date'),
        ),
        migrations.AlterField(
            model_name='maintenancelift',
            name='maintenance_contract_end_date',
            field=models.DateTimeField(verbose_name='Maintainance Contract End'),
        ),
        migrations.AlterField(
            model_name='maintenancelift',
            name='maintenance_contract_start_date',
            field=models.DateTimeField(verbose_name='Maintainance Contract Start'),
        ),
        migrations.AlterField(
            model_name='note',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.contract'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(verbose_name='Date of note'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CRMapp.contract'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase Date End'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='start_date',
            field=models.DateTimeField(verbose_name='Phase Date Start'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_datetime',
            field=models.DateTimeField(),
        ),
    ]
