# Generated by Django 3.2.15 on 2024-01-05 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0010_auto_20231222_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='sales_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='sales_name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9715Xxxxxxxx'.", regex='^\\+9715\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ats',
            field=models.CharField(max_length=64, null=True, verbose_name='ATS'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='floors',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='floors'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='lift_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='location',
            field=models.URLField(blank=True, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size'),
        ),
    ]
