# Generated by Django 3.2.15 on 2023-11-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0011_auto_20231128_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of client register'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='Date of remark'),
        ),
        migrations.AlterField(
            model_name='maintenancelift',
            name='free_maintenance_expiry_date',
            field=models.DateField(verbose_name='free maintenance expiry date'),
        ),
        migrations.AlterField(
            model_name='maintenancelift',
            name='handing_over_date',
            field=models.DateField(verbose_name='Handing Over Date'),
        ),
        migrations.AlterField(
            model_name='maintenancelift',
            name='maintenance_contract_end_date',
            field=models.DateField(verbose_name='Maintainance Contract End'),
        ),
        migrations.AlterField(
            model_name='maintenancelift',
            name='maintenance_contract_start_date',
            field=models.DateField(verbose_name='Maintainance Contract Start'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(verbose_name='Date of note'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Phase Date End'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='start_date',
            field=models.DateField(verbose_name='Phase Date Start'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_datetime',
            field=models.DateField(),
        ),
    ]
