# Generated by Django 3.2.15 on 2024-01-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0011_auto_20240105_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='inquiry',
        ),
    ]
