COMPANY_NAME=(
    ('ATLAS', 'ATLAS'),
    ('KEILANI_INTERIORS', 'KEILANI_INTERIORS'),
    ('NAMMOUS', 'NAMMOUS'),
    ('KCC', 'KCC'),
    ('SMART', 'SMART'),
    ('AC', 'AC'),
    ('LAND_SCAPE', 'LAND_SCAPE'),
    ('SWIMMING_POOL', 'SWIMMING_POOL'),
    )

PHASES_NAME=(
    
    ('SALES', 'SALES'),
    ('ENG', 'ENG'),
    ('SIGNED_CONTRACT', 'SIGNED_CONTRACT'),
    ('MANUFACTURING', 'MANUFACTURING'),
    ('DELIVERY', 'DELIVERY'),
    ('INSTALLATION', 'INSTALLATION'),
    ('MECHANICAL', 'MECHANICAL'),
    ('ELECTRICAL', 'ELECTRICAL'),
    ('HANDING_OVER', 'HANDING_OVER'),
    ('MAINTENANCE', 'MAINTENANCE'),
    )

MAINTAINCANCE_CHOICES=(
    ('FREE', 'FREE'),
    ('PAID', 'PAID'),
    )

SPARE_PARTS=(
    ('COMPREHENSIVE', 'COMPREHENSIVE'),
    ('REGULAR', 'REGULAR'),
    )


MAINTENANCETYPE_CHOICES=(
    ('EMERGENCY', 'EMERGENCY'),
    ('PREDICTIVE PERIODIC', 'PREDICTIVE PERIODIC'),
    ) 